"""Every table of plan section 8.6, and the fixed lists (implementation 02, Phase 3).

Generated from ``db/models.py`` by ``alembic revision --autogenerate``, then the fixed lists of
plan section 15.3 added at the end of :func:`upgrade`: the genres, the tag categories and the
region ``worldwide``.

Revision ID: 0001
Revises:
Create Date: 2026-10-06 13:29:22.803267
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from aitu_backend.db.models import GENRES, REGIONS, TAG_CATEGORIES

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_files",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("hash"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "tag_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('master', 'user')", name="role_allowed"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("public_id", sa.Integer(), nullable=True),
        sa.Column("external_key", sa.String(length=300), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope IN ('private', 'public')", name="scope_allowed"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["public_id"],
            ["albums.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("albums", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_albums_external_key"), ["external_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_albums_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("public_id", sa.Integer(), nullable=True),
        sa.Column("external_key", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope IN ('private', 'public')", name="scope_allowed"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["public_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artists_external_key"), ["external_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_artists_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "chart_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "library_shares",
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shared_with_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shared_with_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("owner_id", "shared_with_id"),
    )
    with op.batch_alter_table("library_shares", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_library_shares_shared_with_id"), ["shared_with_id"], unique=False
        )

    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("public_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope IN ('private', 'public')", name="scope_allowed"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["public_id"],
            ["playlists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playlists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_playlists_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("based_on", sa.String(length=36), nullable=True),
        sa.Column("public_source_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("step", sa.String(length=16), nullable=True),
        sa.CheckConstraint("kind IN ('song', 'integratedPlaylist')", name="kind_allowed"),
        sa.CheckConstraint("layer IN ('vault', 'private', 'public')", name="layer_allowed"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index("ix_projects_owner_layer", ["owner_id", "layer"], unique=False)

    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('metadata', 'userVersion', 'fixedVersion')", name="kind_allowed"
        ),
        sa.CheckConstraint(
            "status IN ('open', 'changesAsked', 'accepted', 'partlyAccepted', 'refused', 'withdrawn')",
            name="status_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_requests_author_id"), ["author_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("public_id", sa.Integer(), nullable=True),
        sa.Column("external_key", sa.String(length=300), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.Column("default_version", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("scope IN ('private', 'public')", name="scope_allowed"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["public_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_songs_external_key"), ["external_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_songs_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_songs_title"), ["title"], unique=False)

    op.create_table(
        "tag_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["tag_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "value"),
    )
    op.create_table(
        "artist_names",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artist_names", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artist_names_artist_id"), ["artist_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artist_names_name"), ["name"], unique=False)

    op.create_table(
        "audio_refs",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["hash"],
            ["audio_files.hash"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "hash"),
    )
    with op.batch_alter_table("audio_refs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audio_refs_hash"), ["hash"], unique=False)

    op.create_table(
        "chart_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("chart_source_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Date(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chart_source_id"],
            ["chart_sources.id"],
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("song_id", "chart_source_id", "week"),
    )
    with op.batch_alter_table("chart_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chart_entries_song_id"), ["song_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chart_entries_week"), ["week"], unique=False)

    op.create_table(
        "likes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "project_id"),
    )
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_likes_project_id"), ["project_id"], unique=False)

    op.create_table(
        "parts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "position"),
    )
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_parts_project_id"), ["project_id"], unique=False)

    op.create_table(
        "playlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("from_ms", sa.Integer(), nullable=True),
        sa.Column("to_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playlist_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playlist_items_playlist_id"), ["playlist_id"], unique=False
        )

    op.create_table(
        "private_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("version_name", sa.String(length=200), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    with op.batch_alter_table("private_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_private_versions_song_id"), ["song_id"], unique=False)

    op.create_table(
        "request_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["request_id"], ["requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("request_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_comments_request_id"), ["request_id"], unique=False
        )

    op.create_table(
        "request_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["request_id"], ["requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("request_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_items_request_id"), ["request_id"], unique=False
        )

    op.create_table(
        "song_albums",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["album_id"], ["albums.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "album_id"),
    )
    with op.batch_alter_table("song_albums", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_song_albums_album_id"), ["album_id"], unique=False)

    op.create_table(
        "song_genres",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "genre_id"),
    )
    op.create_table(
        "song_regions",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "region_id"),
    )
    op.create_table(
        "song_tags",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("tag_value_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_value_id"], ["tag_values.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "tag_value_id"),
    )
    with op.batch_alter_table("song_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_song_tags_tag_value_id"), ["tag_value_id"], unique=False
        )

    op.create_table(
        "song_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=24), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("song_id", "name"),
    )
    with op.batch_alter_table("song_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_song_versions_song_id"), ["song_id"], unique=False)

    op.create_table(
        "user_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_name", sa.String(length=24), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("song_id", "user_id", "version_name"),
    )
    with op.batch_alter_table("user_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_versions_song_id"), ["song_id"], unique=False)

    op.create_table(
        "song_artists",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("artist_name_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["artist_name_id"], ["artist_names.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("song_id", "artist_name_id"),
    )
    with op.batch_alter_table("song_artists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_song_artists_artist_name_id"), ["artist_name_id"], unique=False
        )

    # ### end Alembic commands ###

    genres = sa.table("genres", sa.column("name", sa.String))
    op.bulk_insert(genres, [{"name": name} for name in GENRES])
    categories = sa.table("tag_categories", sa.column("name", sa.String))
    op.bulk_insert(categories, [{"name": name} for name in TAG_CATEGORIES])
    regions = sa.table("regions", sa.column("code", sa.String), sa.column("name", sa.String))
    op.bulk_insert(regions, [{"code": code, "name": name} for code, name in REGIONS])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("song_artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_song_artists_artist_name_id"))

    op.drop_table("song_artists")
    with op.batch_alter_table("user_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_versions_song_id"))

    op.drop_table("user_versions")
    with op.batch_alter_table("song_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_song_versions_song_id"))

    op.drop_table("song_versions")
    with op.batch_alter_table("song_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_song_tags_tag_value_id"))

    op.drop_table("song_tags")
    op.drop_table("song_regions")
    op.drop_table("song_genres")
    with op.batch_alter_table("song_albums", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_song_albums_album_id"))

    op.drop_table("song_albums")
    with op.batch_alter_table("request_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_items_request_id"))

    op.drop_table("request_items")
    with op.batch_alter_table("request_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_comments_request_id"))

    op.drop_table("request_comments")
    with op.batch_alter_table("private_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_private_versions_song_id"))

    op.drop_table("private_versions")
    with op.batch_alter_table("playlist_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlist_items_playlist_id"))

    op.drop_table("playlist_items")
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parts_project_id"))

    op.drop_table("parts")
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_likes_project_id"))

    op.drop_table("likes")
    with op.batch_alter_table("chart_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chart_entries_week"))
        batch_op.drop_index(batch_op.f("ix_chart_entries_song_id"))

    op.drop_table("chart_entries")
    with op.batch_alter_table("audio_refs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_refs_hash"))

    op.drop_table("audio_refs")
    with op.batch_alter_table("artist_names", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artist_names_name"))
        batch_op.drop_index(batch_op.f("ix_artist_names_artist_id"))

    op.drop_table("artist_names")
    op.drop_table("tag_values")
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_songs_title"))
        batch_op.drop_index(batch_op.f("ix_songs_owner_id"))
        batch_op.drop_index(batch_op.f("ix_songs_external_key"))

    op.drop_table("songs")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requests_author_id"))

    op.drop_table("requests")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_owner_layer")

    op.drop_table("projects")
    with op.batch_alter_table("playlists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlists_owner_id"))

    op.drop_table("playlists")
    with op.batch_alter_table("library_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_library_shares_shared_with_id"))

    op.drop_table("library_shares")
    op.drop_table("chart_sources")
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artists_owner_id"))
        batch_op.drop_index(batch_op.f("ix_artists_external_key"))

    op.drop_table("artists")
    with op.batch_alter_table("albums", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_albums_owner_id"))
        batch_op.drop_index(batch_op.f("ix_albums_external_key"))

    op.drop_table("albums")
    op.drop_table("users")
    op.drop_table("tag_categories")
    op.drop_table("regions")
    op.drop_table("genres")
    op.drop_table("audio_files")
    # ### end Alembic commands ###
