"""Pydantic models shared by the API and the storage layer.

camelCase on the wire via ``Field(alias=...)`` plus
``model_config = ConfigDict(populate_by_name=True)``, mirrored in the
frontend's ``src/music/types.ts``.
"""

from aitu_backend.schemas.matrix import (
    CODE_TO_GRANULARITY,
    GRANULARITY_BEATS,
    GRANULARITY_CODES,
    GRANULARITY_HIERARCHY,
    Granularity,
    Hand,
    KeyLabel,
    MatrixProcessingStep,
    PianoMatrixEnvelope,
    SparseCooMatrix,
    key_labels,
)
from aitu_backend.schemas.metadata import (
    Annotations,
    AudioMetadata,
    AudioReference,
    AudioSource,
    ColumnRange,
    FingerAnnotation,
    KeySignatureChange,
    LibraryTrackMetadata,
    LyricAnnotation,
    MatrixAnchor,
    ParentMatrix,
    PassageAnnotation,
    PlaylistItem,
    PlaylistMetadata,
    Promotion,
    TimeRange,
    TrackMetadata,
    VersionHistoryEntry,
    VersionMetadata,
)
from aitu_backend.schemas.naming import (
    granularity_code,
    granularity_from_code,
    matrix_filename,
    next_version,
    parse_version_folder,
    slugify,
    version_folder,
)
from aitu_backend.schemas.score import MatrixScore, SequenceRequest, SparseMatrix

__all__ = [
    "Annotations",
    "AudioMetadata",
    "AudioReference",
    "AudioSource",
    "ColumnRange",
    "FingerAnnotation",
    "KeySignatureChange",
    "LibraryTrackMetadata",
    "LyricAnnotation",
    "MatrixAnchor",
    "ParentMatrix",
    "PassageAnnotation",
    "PlaylistItem",
    "PlaylistMetadata",
    "Promotion",
    "TimeRange",
    "TrackMetadata",
    "VersionHistoryEntry",
    "VersionMetadata",
    "granularity_code",
    "granularity_from_code",
    "matrix_filename",
    "next_version",
    "parse_version_folder",
    "slugify",
    "version_folder",
    "CODE_TO_GRANULARITY",
    "GRANULARITY_BEATS",
    "GRANULARITY_CODES",
    "GRANULARITY_HIERARCHY",
    "Granularity",
    "Hand",
    "KeyLabel",
    "MatrixProcessingStep",
    "MatrixScore",
    "PianoMatrixEnvelope",
    "SequenceRequest",
    "SparseCooMatrix",
    "SparseMatrix",
    "key_labels",
]
